create table if not exists PRICES
(
   ID INTEGER NOT NULL,
   BRAND_ID INTEGER NOT NULL,
   START_DATE DATETIME NOT NULL,
   END_DATE DATETIME NOT NULL,
   PRICE_LIST INTEGER NOT NULL,
   PRODUCT_ID INTEGER NOT NULL,
   PRIORITY INTEGER NOT NULL,
   PRICE DOUBLE NOT NULL,
   CURR VARCHAR(10) NOT NULL,
   PRIMARY KEY (ID)
);